### ISSUE TITLE
Link to annotated source in README.md is broken

### ISSUE THREAD

**Issue by uxp** [rethinkdb/rethinkdb-example-webpy-blog#3]
I'm not sure where this is supposed to point to. The examples page (http://www.rethinkdb.com/docs/examples/) points back to this repo. The link to the annotates source just 404s at nginx: http://www.rethinkdb.com/docs/examples/webpy-blog/

```
After checking out the code, you can also read the annotated source [here](http://www.rethinkdb.com/docs/examples/webpy-blog/).
```

**Comment by deontologician** [comment]
ping @mglukhovsky

**Comment by coffeemug** [comment]
Ah, thanks for pointing this out. We dropped annotated code rendering because it significantly complicated the build process. I removed the link.
